### ISSUE TITLE
Calculate distance should be accessible for users of this library

### ISSUE THREAD

**Issue by GreG28** [prettymuchbryce/easystarjs#23]
I'm actually using this library for a project with Phaser, and I would like to use this part of the library.. I need to calculate the distance between two tiles for getting the maximum distance where my unit can go !

Sorry for my english..

**Comment by prettymuchbryce** [comment]
Hello. Sorry for the delay. You can use a distance function to achieve this goal. I won't expose this as part of easystarjs itself.
