### ISSUE TITLE
need option to prevent/allow diagonal when next to obstacle

### ISSUE THREAD

**Issue by PrimeLens** [prettymuchbryce/easystarjs#25]
Hi, when walking on 0 
[1, 0]
[0, 0]
there should be an option to allow or prevent the diagonal when next to one obstacle.

Also
[1, 0]
[0, 1]
to allow or prevent when walking between diagonally between two obstacles

**Comment by prettymuchbryce** [comment]
Hello. Sorry for the delay. I can see how this would be useful, and I agree that this should be a feature. Something like `enableCornerCutting()` and `disableCornerCutting()` methods on an easystar instance.
