### ISSUE TITLE
Zalgo bugs

### ISSUE THREAD

**Issue by mikolalysenko** [prettymuchbryce/easystarjs#26]
I'm trying to benchmark easystarjs for an experiment, but keep running into [Zalgo bugs](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony) due to easystar.js not implementing asynchronous calls correctly.  

For example, in some executions of easystar it is possible for the callback to be called synchronously (!!!).  See the following line for reference:

https://github.com/prettymuchbryce/easystarjs/blob/master/src/easystar.js#L149-L152

This can cause terrible problems if you aren't expecting the callback to execute until all calls to easystar have been dispatched.  A simple fix would be to wrap these calls in a setTimeout, for example.

**Comment by prettymuchbryce** [comment]
Hi Mikola. Thanks for bringing this issue to my attention. I agree that the callbacks should always be asynchronous. I will take a look.
