### ISSUE TITLE
Weird behaviour with diagonals enabled

### ISSUE THREAD

**Issue by CubixSystem** [prettymuchbryce/easystarjs#27]
#16 strikes back!

For example:
![test](https://cloud.githubusercontent.com/assets/7340055/9426973/0f68d5ee-496b-11e5-8db0-62c35811d963.PNG)

Another:
![test2](https://cloud.githubusercontent.com/assets/7340055/9426974/0f6c988c-496b-11e5-83f5-bd7f1d35f072.PNG)
Coordinates for reproduce:
Start point (4,4)
End point (2, 2)

**Comment by prettymuchbryce** [comment]
Hey CubixSystem. Thanks for opening an issue. Let me see if I can create a test which reproduces this issue. The start and end points you provided are helpful information. What size is your map ? Are there any other settings such as tile costs ?

**Comment by CubixSystem** [comment]
Thanks for your great work and fast response.
I am very impressed by possibility of setting tile costs!

version is ```0.2.1```, from ```npm```
In examples above I use this code:

```javascript
  var EasyStar = require('easystarjs');
  var easystar = new EasyStar.js();
  var grid = [];
  for (var i = 0; i < 20; i++) {
    grid[i] = [];
    for (var j = 0; j < 20; j++) {
      grid[i][j] = 0;
    }
  }
  easystar.setGrid(grid);
  easystar.setAcceptableTiles([0]);
  easystar.enableDiagonals();
```
Similar to #16, without ```easystar.enableDiagonals();``` all works fine.

**Comment by CubixSystem** [comment]
Order of points is very important:
Start point (2, 2)
End point (4, 4)
![test](https://cloud.githubusercontent.com/assets/7340055/9427266/1aa04b52-497c-11e5-9076-3255fcf0a6ae.PNG)

Start point (4,4)
End point (2, 2)
![test2](https://cloud.githubusercontent.com/assets/7340055/9427269/27fb7f42-497c-11e5-8007-414ad4e929e2.PNG)

**Comment by prettymuchbryce** [comment]
Hey CubixSystem. Thanks for all of the details you provided. Can you let me know if the latest commit fixes your issue ?

**Comment by CubixSystem** [comment]
@prettymuchbryce still the same:
![test2](https://cloud.githubusercontent.com/assets/7340055/9457350/4b0b18d4-4aea-11e5-801a-d4ffdc3d013a.PNG)

**Comment by prettymuchbryce** [comment]
Are you using `0.2.2` from npm ? 
Is the 4,4 to 2,2 search working as expected now ?
Can you provide me with the start/end coordinates of the 3 searches being performed on the grid from the above image ?

**Comment by CubixSystem** [comment]
It was problem on my side, I update  to ```0.2.2``` but forget to update client-packed scripts.
Now  It all  works as expected!
Thank you! :+1: 
I continue my tests and let you know If I met any other issues.

**Comment by prettymuchbryce** [comment]
No problem. I'm happy to help. Please feel free to open another issue if you experience any other problems. Good luck with your game. It looks cool. :sunglasses:
