### ISSUE TITLE
PriorityQueue.MIN_HEAP, 2 element queue is not in right order

### ISSUE THREAD

**Issue by antonytrupe** [prettymuchbryce/easystarjs#28]
When adding a second element that is smaller than the first element, the order is wrong.
I believe the bug is in getParentOf.

pseudo code to reproduce

var p = new PriorityQueue("value", PriorityQueue.MIN_HEAP);

var object1 = {};
var object2 = {};

object1.value = 10;
object2.value = 5;

p.insert(object1);
assert.equal(p.peek(), object1);

p.insert(object2);
assert.equal(p.peek(), object2);

assert.equal(p.shiftHighestPriorityElement(), object2);

**Comment by antonytrupe** [comment]
I believe it should be
Math.floor((index-1) / 2)
in place of 
Math.floor(index/2)-1

**Comment by prettymuchbryce** [comment]
Nice catch! Thanks. Fixed in 0.2.3
