### ISSUE TITLE
Directional condition on tiles

### ISSUE THREAD

**Issue by pellejacobs** [prettymuchbryce/easystarjs#37]
How would you go about implementing a directional condition on some tiles? 

Take for example a ledge a character can jump of from, but cannot climb onto. 

Here is an example from [vim-adventures](http://vim-adventures.com/). You can move from left to right onto the ledge, but not from right to left.

![vim_adventures](https://cloud.githubusercontent.com/assets/7174652/18382614/06e0a07e-7682-11e6-9f27-6f5fb11a8a87.jpg)

Would you be willing to accept a PR for this?

**Comment by prettymuchbryce** [comment]
Hey Pelle. This would be a great addition to easystar. I would be happy to accept a PR for this feature.

**Comment by pellejacobs** [comment]
Closed with #39
