### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by prettymuchbryce** [prettymuchbryce/easystarjs#43]
Lets get CI working in easy star. Possibly through Travis or CircleCI.

**Comment by esromneb** [comment]
I've made a PR to add Travis here: https://github.com/prettymuchbryce/easystarjs/pull/86

**Comment by esromneb** [comment]
I've made a 2nd PR using github actions here: https://github.com/prettymuchbryce/easystarjs/pull/88

**Comment by esromneb** [comment]
Ok, thanks for pointing out my mistake. I've made a 3rd PR with no extra code here:  https://github.com/prettymuchbryce/easystarjs/pull/89

**Comment by prettymuchbryce** [comment]
Excellent. Thanks!
