### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [prettymuchbryce/easystarjs#45]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of easystarjs (v 0.3.0) our tools detected approximately 19 unused function in the dependencies (heap). Removing those functions, the size of easystarjs bundled could be reduced at least 16% (All tests passed).
I’m attaching the reduced version of your project. 
[easystar-0.3.0(optimized).txt](https://github.com/prettymuchbryce/easystarjs/files/671077/easystar-0.3.0.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this problem?

Thanks in advance.

Cheers,

**Comment by prettymuchbryce** [comment]
Hello There.

- Yes I was aware
- It's not ideal, but only adds a small amount of size to the compiled output
- It should be solvable already with webpack/babel and tree shaking. I plan to implement this in the future

Good luck with your project!
