### ISSUE TITLE
Add ability to cancel an instance

### ISSUE THREAD

**Issue by sbj42** [prettymuchbryce/easystarjs#46]
I can start a path calculation with `findPath()`, but once I've started one I don't see a way to cancel it.

Suppose that the path takes multiple passes to compute, and before it's finished circumstances change and (a) the moving entity dies or no longer needs to move, or (b) the entity needs to move to a different location.

In that case, to avoid wasted computation it would be nice to be able to cancel a findPath instance.  For example, findPath could return an integer ID, and I could later call `cancelFindPath()` with that ID to cancel it.

As far as I can see, cancelling would be easy to implement by just finding the object in the instances array and splicing it out.

**Comment by prettymuchbryce** [comment]
Hey @sbj42 thanks for the issue. I understand your point. I think it's a reasonable request. I like your API suggestion of how to solve it as well. It follows similar semantics of `setTimeout` or `setInterval` in the JavaScript API, which I think most users would be familiar with. Feel free to open a PR if you'd like, or I will get around to implementing this at some point. 😄

**Comment by prettymuchbryce** [comment]
Fixed in #47
