### ISSUE TITLE
how to add new method or funtion to the easy star

### ISSUE THREAD

**Issue by arunkumar413** [prettymuchbryce/easystarjs#55]
Hi Team,

I want to add a new feature to convert the easystar generated path points to SVG path element. Could you please let me know where and how to add this feature. 

Thanks,
Arun

**Comment by prettymuchbryce** [comment]
Hi Arun. Unfortunately I don't have the time or resources to help you with your project. I will close this issue. I recommend reading the SVG specification or finding a javascript library that allows you to manipulate SVG elements. Best of luck.

**Comment by arunkumar413** [comment]
Hi Bryce,

It's just few lines of code and  could be very handy for people working with SVG and easystar. Please take a look.

https://gist.github.com/arunkumar413/fd88baf8c2fd6bbd972364960284efed

**Comment by prettymuchbryce** [comment]
Hi Arun. Apologies. I think I originally misunderstood your question.

As far as adding this functionality to the library itself I think it's too domain specific for what I'm trying to accomplish with this project. Hopefully that makes sense, and I appreciate your desire to contribute.
