### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by sbj42** [prettymuchbryce/easystarjs#59]
Looks like commit 704dca7 accidentally moved the karma and jasmine references from devDependencies to depenencies.  As a result, anyone using easystarjs 0.4.1 or 0.4.2 ends up installing a bunch of extra packages (including e.g. nodemailer and phantomjs).  Testing packages should be confined to devDependencies.

It also makes easystarjs look unnecessarily bad on npms.io due to https://nodesecurity.io/check/easystarjs.

**Comment by prettymuchbryce** [comment]
Thanks for finding this mistake @sbj42. A very nice catch on the security check as well. I've fixed it and pushed a new patch version.
