### ISSUE TITLE
Non-grid node creation

### ISSUE THREAD

**Issue by McFunkypants** [prettymuchbryce/easystarjs#6]
I have an interesting request. I'd like to be able to declare the world in a non-grid fashion (eg: add nodes and neighbours: a tree) so I can make waypoint pathfinding that isn't on the grid. 

Coupled with your upcoming variable costs, this could be used to, for example, pathfind for an RTS with arbitrarily-sized blocking sprites. 

Imagine just defining nodes where "doors" are, rather than including a bazillion empty room tiles. Great for road networks or dealing with walls that are at floating-point x,y coordinates.

Keep up the WONDERFUL WORK!

**Comment by sbj42** [comment]
This is indeed interesting, but it seems out of scope for easystar.  Searching over a generalized graph would warrant different data structures, which might be slower than an algorithm specifically built for a grid?
