### ISSUE TITLE
Is there a way to abort a searching task ? 

### ISSUE THREAD

**Issue by xjay111** [prettymuchbryce/easystarjs#65]
Sometimes i want to abort a searching task , how can i do that?

**Comment by Strikeeaglechase** [comment]
Save the search id then cancel the task
Example: 
`var instanceId = easystar.findPath(startX, startY, endX, endY, callback);
easystar.cancelPath(instanceId);`

**Comment by xjay111** [comment]
Thanks fir resonse . Already fix that .
