### ISSUE TITLE
Broken links on website due to latest release being incorrectly tagged

### ISSUE THREAD

**Issue by Dean-Coakley** [prettymuchbryce/easystarjs#80]
Apologies for posting here, doesn't seem very relevant, but I don't see a better location.

Both download buttons on: https://easystarjs.com/ 404

* https://raw.githubusercontent.com/prettymuchbryce/easystarjs/v0.4.3/bin/easystar-0.4.3.js
* https://raw.githubusercontent.com/prettymuchbryce/easystarjs/v0.4.3/bin/easystar-0.4.3.min.js

This is because, while these files exist on master(as of right now):
* https://github.com/prettymuchbryce/easystarjs/tree/master/bin

They do not exist on the tag:
* https://raw.githubusercontent.com/prettymuchbryce/easystarjs/v0.4.3/bin/easystar-0.4.3.js

Instead there is just:
* https://raw.githubusercontent.com/prettymuchbryce/easystarjs/v0.4.3/bin/easystar-0.4.2.js

**Comment by prettymuchbryce** [comment]
Oops. Somehow the tag was placed at the wrong commit. I have corrected it.

Thank you for taking the time to file this issue. It's much appreciated.
